test.js
As per #21:
> The /UPSTART_JOB/ check was premature, and doesn't do the right thing.
This PR removes the test for it (needless test).
=> removed UPSTART_JOB test

index.js, readme.md, test.js
So we're to the point in technology where we shouldn't be bound to the standard 16 colors of the terminal.
We now support `TERM=xterm-256color` and *should* be moving toward [truecolor (16 million) color support](http://stackoverflow.com/questions/15682537/ansi-color-specific-rgb-sequence-bash/26665998#26665998). Although there isn't a standard `TERM` setting for it, we should still support it on the command line.
This *does*, however, break code that does either a `== true` or `=== true` (or `false`) check. Ternary operators and type coercion should be unaffected (as is the *cli.js*).
I understand this may be unacceptable, but us more aesthetic individuals are pining for more 256 (or even 16m) support in our programs. Most modern day terminals support 256 color, and a large number of …
=> added 256/16m color support and results

index.js, readme.md, test.js
So this extends the `FORCE_COLOR` environment variable to allow `FORCE_COLOR=0` (preserving the behavior of just `FORCE_COLOR=`), which will forcibly _disable_ color environment-wide.
This was inspired by the bug over at atom/electron#1647
=> Add ability to force disable colors with an environment variable

index.js, package.json, test.js
Fixes #49
Returns support level 2 (256-bit colour) if running on Windows 10 build 10586 or later and Node.js 7.5.0 or later. Node.js 7.5.0 is the first version of Node.js to include the [libuv patch](https://github.com/libuv/libuv/commit/445e3a1f06b2a049e2b50b7edf2992ce80167014) that enables ANSI support on Windows 10.
- Added checks for Windows
- Fixed existing tests on Windows
- Added new tests to test Windows platform behaviour
Tests ran successfully on Windows and Linux.
=> Support 256 color output on Windows 10

index.js, test.js
from [circleCI docs](https://circleci.com/docs/1.0/environment-variables/#basics)
>Ideally, you won’t have code which behaves differently in CI. But for the cases when it’s necessary, >we set two environment variables which you can test:
>
>CIRCLECI
>
>  true
>
>CI
>
>  true
=> CIRCLECI support

index.js, test.js
Fixes #59
```bash
E:\work\supports-color (win10) (supports-color@4.2.0)
$ node -p process.version
v8.1.2
E:\work\supports-color (win10) (supports-color@4.2.0)
$ node -p process.versions.node
8.1.2
E:\work\supports-color (win10) (supports-color@4.2.0)
$ node -p require('./')
{ level: 2, hasBasic: true, has256: true, has16m: false }
```
`process.version` has a prefix `v`, so I use `process.versions.node` to replace it
=> Fix 256 color detection on Windows 10 

index.js
TravisCI has some special logic in master builds that filters logs (to prevent ENV variables to be printed). This logic results in `process.stdout.isTTY` to be `false` (only in master branch builds, not in PR builds).
if we change the order these checks are done, we should be able to return consistent value on both master and PR builds on travis
=> Check for CI before isTTY

index.js, test.js
There is a putty-256color terminfo on ubuntu (and probably other systems) that allows for the minor differences between putty and xterm. However currently this fails to then register the support with supports-color / chalk because it's specifically looking for xterm-256color or screen-256color.
This just extends the regex to also match putty-256color.
I'm not sure if it might be better to instead just match on env.TERM ending with 256 color? That could product some unexpected false positives, so I didn't go that far.
Here is a list of terminfo matches on ubuntu14.04 as that happens to be the os of the server I'm connecting to.
/$ find /usr/share/terminfo/ | grep 256color
/usr/share/terminfo/E/Eterm-256color
/usr/share/terminfo/x/xterm+256color
/usr/share/terminfo/v/vte-256color …
=> Add support for putty-256color terminfo

index.js, test.js
rxvt supports color: https://wiki.archlinux.org/index.php/rxvt-unicode#Colors
=> Add rxvt color support

index.js, test.js
Closes #51. This is a breaking change.
---
This PR adds the ability to test individual output streams for validity. This is one particular approach - see the end of this PR for another non-breaking proposed approach.
This exposes the new API as:
```javascript
const supportsColor = {
supportsColor: (stream) => {...},
stdout: supportsColor(process.stdout),
stderr: supportsColor(process.stderr)
}
```
So the only change necessary to migrate would be to change
```javascript
const supportsColor = require('supports-color');
if (supportsColor) {
// ...
}
if (supportsColor.level >= 2) {
// ...
}
```
to either
```javascript
const supportsColor = require('supports-color');
if (supportsColor.stdout) {
// ...
}
if (supportsColor.stdout.level >= 2) {
// ...
}
```
or simply
```javascript
const …
```
=> Allow testing of individual streams

index.js, test.js
Before, the level would be 1 when forcing color when the stream is not a TTY.
```
$ FORCE_COLOR=1 node -p "require('supports-color').stdout" | cat
{ level: 1, hasBasic: true, has256: false, has16m: false }`
```
Now, the proper level is calculated based on the environment, even when the stream is not a TTY.
```
$ FORCE_COLOR=1 node -p "require('supports-color').stdout" | cat
{ level: 3, hasBasic: true, has256: true, has16m: true }
```
=> Calculate proper `level` when forcing color

index.js
According to https://gist.github.com/XVilka/8346728#detection and empirical tests on Konsole,
when `COLORTERM=truecolor`, 24-bit color support is guaranteed to work.
=> Check the COLORTERM variable for 16M color support

index.js
VSCode appears to now set stream.isTTY in the debugger.
Fixes #79
=> Remove now moot VSCode check

index.js
This PR adds [`vt220`](https://en.wikipedia.org/wiki/VT220) to the list of supported terminals, used by OpenBSD (and NetBSD, IIRC) when running in console mode:
For reference, here's proof (sorry for the blurry phone picture, taking screenshots of consoles isn't that easy 😉):
=> Add support for VT220

index.js, test.js
Rearranges evaluation order so check for dumb terminal precedes other terminal and
platform-specific checks. Will allow Emacs shell to function properly.
Fixes #88
Closes #89
=> Give `TERM=dumb` higher priority

index.js
Your code has support for `always`, it seems expected that `never` would work too.
I would like to use these as flags, they seem standard and have been included in `grep`
```
--colour=[when, --color=[when]]
Mark up the matching text with the expression stored in GREP_COLOR environment variable.  The possible values of when can be `never', `always' or
`auto'.
```
=> Add support for `color=never` CLI flag

index.js
Environment variables will never contain booleans. They should only contain strings as all entries are converted to a string in the setter.
=> Remove dead code

index.js
Use `tty` instead of stdio streams to detect if stdio outputs are ttys to improve require speed.
`tty` is used by stdio streams, so if streams are initialized later or were initialized before there will be no overhead. However if streams are not used(`process.stdout` and `process.stderr` stream objects, not OS streams itself), it speeds up require times slightly.
=> Avoid triggering stdio streams creation

index.js
Like other CI providers, GITHUB_ACTIONS supports color in logs
=> Support GitHub Actions

index.js, test.js
This adds [Buildkite](https://buildkite.com/) to the whitelist of CI environments that support color output. Buildkite always has the [`CI`](https://buildkite.com/docs/pipelines/environment-variables#bk-env-vars-ci) and [`BUILDKITE`](https://buildkite.com/docs/pipelines/environment-variables#bk-env-vars-buildkite) environment variables set.
=> Add Buildkite to the CI whitelist

browser.js
Google Chrome 69+ supports basic ANSI escape codes.
=> Detect Google Chrome

index.js, readme.md, test.js
Closes #40.
Also adds documentation for the previously undocumented `.supportsColor` function.
=> Add option for ignoring `process.argv`

index.js, test.js
[Drone CI](https://docs.drone.io/pipeline/environment/reference/drone/) supports displaying color on its web interface, so we can enable basic support for it.
=> Add Drone CI to supported environments

browser.js
Re: https://github.com/chalk/supports-color/pull/111#discussion_r638691436
Basically, that was checking for Chrome 69 or higher using a feature that is only available in Chrome 64 or higher, i.e. only covering a sub-optimal five-versions range, and causing it to break over any other non-ES2018 compliant browser.
=> Simplify the browser check

index.js
This explicitly imports process in this package. I was just experimenting getting this package to work in Deno, and it's nice to be able to support Node.js packages in Deno using just import maps without having to require eg the `process` global to be defined (since it's also kind of a security hole as well).
This behaviour is documented as recommended in https://nodejs.org/dist/latest-v16.x/docs/api/process.html#process_process as well.
=> Explicitly import `process`

index.js
Azure DevOps has supported displaying build/release logs with console colors (at least 16 - level 1) in their browser-based UI for  some time. 
I tested coloring our node CI build scripts using chalk, but found that I needed to _force color_ for things to work in the Azure DevOps build logs, even if the same scripts gave colored output on my local machine.
After reviewing the `supports-color` package, I realized that you are doing environment variable tests to detect different CI provider environments like Team City, Github Actions, Travis,  AppVeyor etc, but no test for Azure DevOps.
I have therefore added a test that should verify that the script is running in Azure DevOps.
I have tested this in Azure DevOps, and the variables will work in both Build and Release Pipelines.
Reference: …
=> Support level 1 in Azure DevOps pipelines

index.d.ts, index.test-d.ts
We have logic to check the `haveStream` if a falsy value. So we should mark `stream` as optional.
=> Fix TypeScript definition

browser.js, index.js
Avoid requesting unnecessary permissions when used by Deno users.
Modern Chromium supports true color.
=> fix: addressing some unanticipated situations

index.js, test.js
=> fix: CLI flags/FORCE_COLOR precede other color support checks

index.js
matching
https://github.com/chalk/chalk/pull/653
=> Ghostty supports truecolor

index.js
Add detection of WezColor and report 16m color support. It exports COLORTERM as truecolor, but that doesn't propagate across ssh sessions, so this will help with proper color detection in all environments.
=> WezTerm supports truecolor
